packages:
  - 'packages/*'

allowBuilds:
  nx: true
  '@swc/core': true
  esbuild: true
  scriptc: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@nx/devkit@23.1.2'
  - '@nx/docker@23.1.2'
  - '@nx/eslint-plugin@23.1.2'
  - '@nx/eslint@23.1.2'
  - '@nx/jest@23.1.2'
  - '@nx/js@23.1.2'
  - '@nx/node@23.1.2'
  - '@nx/nx-darwin-arm64@23.1.2'
  - '@nx/nx-darwin-x64@23.1.2'
  - '@nx/nx-freebsd-x64@23.1.2'
  - '@nx/nx-linux-arm-gnueabihf@23.1.2'
  - '@nx/nx-linux-arm64-gnu@23.1.2'
  - '@nx/nx-linux-arm64-musl@23.1.2'
  - '@nx/nx-linux-x64-gnu@23.1.2'
  - '@nx/nx-linux-x64-musl@23.1.2'
  - '@nx/nx-win32-arm64-msvc@23.1.2'
  - '@nx/nx-win32-x64-msvc@23.1.2'
  - '@nx/vitest@23.1.2'
  - '@nx/workspace@23.1.2'
  - nx@23.1.2
  - lint-staged@17.4.1
