/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Explicit order: autogenerated sorts by file name, which put http.md before the home page.
  guide: ['index', 'http'],
};

export default sidebars;
